### ISSUE TITLE
CentOS Guest PrivateTmp fail

### ISSUE THREAD

**Issue by Debianer** [lxc/linuxcontainers.org#127]
When starting services in a CentOS guest, many of them want to create private temp directories. This fails under LXC. Widely used services such as Apache, MariaDB and Cyrus Imap are affected and fail to start. This has been discussed in several places on the internet, mainly the Proxmox forums [1]. So you may already be very well aware of the issue. The workaround is to replace

PrivateTmp=true

with 

PrivateTmp=false

in the respective configuration file under /usr/lib/systemd/system/

It would be nice, if the workaround would be included or referenced in the documentation on linuxcontainers.org. [2]

[1] https://www.google.de/search?q=PrivateTmp+lxc#q=%22PrivateTmp%22+%22lxc%22

[2] https://linuxcontainers.org/lxd/getting-started-cli/

**Comment by Debianer** [comment]
I just tested CentOS 7.2. I don't see any errors anymore when using PrivateTmp with CentOS 7.2 guests. I never had a problem with Debian guests. Closing for now.

**Comment by stgraber** [comment]
Just tested on centos/6, centos/7 and centos/8. httpd starts fine on all 3 and does have PrivateTmp=true enabled.
