### ISSUE TITLE
Fix links to use slash-ending ?

### ISSUE THREAD

**Issue by clarkwinkelmann** [lxc/linuxcontainers.org#131]
I just noticed that all links on the website point to URLs ending with no slash (hardcoded), but that the generated website uses the `index.html` trick to display "clean" slash-ended urls.

Even if the server returns `301` responses, this still means a lot of doubled queries where one would be enough, not counting that nothing else can load before those two requests are finished. As a web dev I mainly think of new visitors for who the speed is a big factor.

The server isn't really slow but this probably wouldn't cost much to make it a bit faster ? Or does it work like this on purpose ? (would be strange)

I can work on a PR if you want. Or maybe is there a better way than editing every file under `content/` ?

**Comment by stgraber** [comment]
Hi,

Yeah, having all the internal links include the trailing slash would be nice, a branch would definitely be welcome!

**Comment by clarkwinkelmann** [comment]
I hadn't noticed this Issue was still open. The problem was solved in my PR back in December.
