### ISSUE TITLE
console getty respawns and crashes, spamming the log

### ISSUE THREAD

**Issue by Debianer** [lxc/linuxcontainers.org#134]
Console getty keeps respawning in the guests, spamming the logs. The issue was discussed here:

https://github.com/lxc/lxd/issues/444

Currently the proposed changes to the templates from images.linuxcontainers.org don't seem to be implemented. It took me an embarrassingly long time to find the correct commands to disable getty.

For a Centos 7 guest they are as follows:

    systemctl stop console-getty
    systemctl disable console-getty
    systemctl mask console-getty

If you don't mask, console-getty will be automatically enabled on the next boot. 

Debian Jessie guests are a bit different.
    
    systemctl stop console-getty.service
    systemctl stop getty@tty1.service
    systemctl stop getty@tty2.service
    systemctl stop getty@tty3.service
    systemctl stop getty@tty4.service

    systemctl disable console-getty.service
    systemctl disable getty@tty1.service
    systemctl disable getty@tty2.service
    systemctl disable getty@tty3.service
    systemctl disable getty@tty4.service

    systemctl mask console-getty.service
    systemctl mask getty@tty1.service
    systemctl mask getty@tty2.service
    systemctl mask getty@tty3.service
    systemctl mask getty@tty4.service

Until the proposed changes to the templates are implemented or another solution is found, it would be really nice for people like me, if the above commands found their way into the documentation. The first place I looked was /etc/inittab, where these settings were changed in Debian before Jessie.

For reference, the respective log looks like this for Debian Jessie:

Dec 19 18:05:15 tttdebian systemd[1]: console-getty.service has no holdoff time, scheduling restart.
Dec 19 18:05:15 tttdebian systemd[1]: getty@tty1.service has no holdoff time, scheduling restart.
Dec 19 18:05:15 tttdebian systemd[1]: getty@tty3.service has no holdoff time, scheduling restart.
Dec 19 18:05:15 tttdebian systemd[1]: getty@tty4.service has no holdoff time, scheduling restart.
Dec 19 18:05:15 tttdebian systemd[1]: Stopping Getty on tty4...
Dec 19 18:05:15 tttdebian systemd[1]: Starting Getty on tty4...
Dec 19 18:05:15 tttdebian systemd[1]: Started Getty on tty4.
Dec 19 18:05:15 tttdebian systemd[1]: Stopping Getty on tty3...
Dec 19 18:05:15 tttdebian systemd[1]: Starting Getty on tty3...
Dec 19 18:05:15 tttdebian systemd[1]: Started Getty on tty3.
Dec 19 18:05:15 tttdebian systemd[1]: Stopping Getty on tty1...
Dec 19 18:05:15 tttdebian systemd[1]: Starting Getty on tty1...
Dec 19 18:05:15 tttdebian systemd[1]: Started Getty on tty1.
Dec 19 18:05:15 tttdebian systemd[1]: Stopping Console Getty...
Dec 19 18:05:15 tttdebian systemd[1]: Starting Console Getty...
Dec 19 18:05:15 tttdebian systemd[1]: Started Console Getty.
Dec 19 18:05:15 tttdebian agetty[373]: /dev/console: Operation not permitted
Dec 19 18:05:15 tttdebian agetty[370]: /dev/tty1: No such file or directory
Dec 19 18:05:15 tttdebian agetty[367]: /dev/tty3: No such file or directory
Dec 19 18:05:15 tttdebian agetty[364]: /dev/tty4: No such file or directory

For Centos 7:

Dec 19 18:06:50 tcentos systemd[1]: Starting Console Getty...
Dec 19 18:06:50 tcentos agetty[566]: /dev/console: Operation not permitted
Dec 19 18:07:00 tcentos systemd[1]: console-getty.service has no holdoff time, scheduling restart.
Dec 19 18:07:00 tcentos systemd[1]: Started Console Getty.

**Comment by stgraber** [comment]
We won't be changing the images as those are also used by LXC itself which does have /dev/console. The right way to fix that is to get systemd fixed in the various distributions at which point things will just work.

Until then, you'll unfortunately have to mask the unit.

**Comment by Debianer** [comment]
Until a fix arrives downstream, it would be nice if this would be mentioned in the documentation somewhere around here:

https://linuxcontainers.org/lxd/getting-started-cli/

I am not sure. Is this the right place to open issues concerning the documentation on linuxcontainers.org?

**Comment by deric** [comment]
Currently Debian Jessie 8.3 ships with `/lib/systemd/system/getty-static.service` where there are 1-6 ttys deifned:

```
ExecStart=/bin/systemctl --no-block start getty@tty2.service getty@tty3.service getty@tty4.service getty@tty5.service getty@tty6.service
RemainAfterExit=true
```
while only tty 1-4 exists. Is is already fixed in upstream LXC template?
