### ISSUE TITLE
nova-lxd is available on *Ubuntu 16.10* ?

### ISSUE THREAD

**Issue by aodzip** [lxc/linuxcontainers.org#173]
Really I need a ask is it 15.10 or future 16.10?

https://github.com/lxc/linuxcontainers.org/blob/bcbed6a27e55ee25d5a07e84ee6b1b760a63b8c5/content/lxd/getting-started-openstack.md#manual-installation---ubuntu-server

**Comment by stgraber** [comment]
@zulcss I think those instructions are meant for 16.04? can you please send a branch

**Comment by aodzip** [comment]
Now I update to Ubuntu 16.04 , I get lxd. lol
