### ISSUE TITLE
LXC Dropdown: Re-arranging things to make info more clear

### ISSUE THREAD

**Issue by Kentoseth** [lxc/linuxcontainers.org#199]
As mentioned previously, I was/am planning on adding the full CLI output of the Python-lxc API to the website.

However, I see that the current way it is arranged is not so clear.

What I propose is:

> Click on 'LXC' - Dropdown appears (currently operational and will not change)
> Click/Scroll on 'Documentation' and a side-menu (similar to how man-pages works)

When doing the click/scroll over 'Documentation', the results we get would be:
- Main/other-name : which would contain most of the top-level information already present when selecting 'Documentation' currently
- C : Providing the full C API spec with the current example, etc.
- Python : Same as C
- All-other-languages : We can place these as time goes by

The only (slight) problem I have is that I am unsure how to split the 'Documentation' into a menu option itself with sub-menus.

Any suggestions on this will help and I will then go about doing it myself.

**Comment by stgraber** [comment]
I think the generator should do the right thing if you set the menu field to '"LXC", "Documentation, "C"'
