### ISSUE TITLE
Results of example lxc commands would clarify things

### ISSUE THREAD

**Issue by rcharney** [lxc/linuxcontainers.org#200]
Examples in the initial training materials would speed things up and avoid confusion if the results of each lxc command were shown.

**Comment by stgraber** [comment]
I'm not opposed to adding it. A branch doing so, either with just plain text dump or fancy terminal screenshots would be welcome.

**Comment by Lin-Buo-Ren** [comment]
A `lxc launch` tutorial is appreciated, I have to Google to initialize a container without error.

**Comment by toby63** [comment]
Are the new changes (https://linuxcontainers.org/lxd/advanced-guide/#lxc-launch-flags) sufficient for you, or would you like to have more details?
