### ISSUE TITLE
LXD Try-it online connection fails 

### ISSUE THREAD

**Issue by rst0git** [lxc/linuxcontainers.org#219]
- Firefox 49.0.2
- Linux
Received message : "error: Error opening startup config file: "loading config file for the container failed"

![screenshot](https://cloud.githubusercontent.com/assets/9142901/19781980/bf09fde0-9c83-11e6-8517-fe3a75fb3e20.png)

**Comment by stgraber** [comment]
Looks like things are back to working order, not sure what happened though...

**Comment by techtonik** [comment]
Wow. Never seen that websocket debugging interface before.
