### ISSUE TITLE
CORS allowed in domain

### ISSUE THREAD

**Issue by alex-left** [lxc/linuxcontainers.org#280]
Hi, the app "lxd-gui" (https://github.com/dobin/lxd-webgui) can't do make GET to images.linuxcontainers.org because don't allow others origins. 
Can you enable it? 
```
╰─$ curl -XOPTIONS https://uk.images.linuxcontainers.org/1.0/images -I
HTTP/1.1 200 OK
Date: Tue, 31 Oct 2017 14:10:48 GMT
Server: Apache/2.4.7 (Ubuntu)
Strict-Transport-Security: max-age=31536000
Allow: POST,OPTIONS,GET,HEAD,TRACE
Content-Length: 0
Content-Type: application/json
```

**Comment by stgraber** [comment]
Not easily as this is run by a number of mirrors which I don't have any control over...

**Comment by stgraber** [comment]
I've added the option to our recommended vhost config and confirmed that the server I run does have the header. It may take quite a while until the other servers manually get updated by their operators though.

**Comment by alex-left** [comment]
great! thx
