### ISSUE TITLE
Vanilla: Need to fix and re-introduce collapsible sections in try-it

### ISSUE THREAD

**Issue by stgraber** [lxc/linuxcontainers.org#283]
I had to remove the collapsible link on the feedback and step-by-step widgets as those weren't working after the vanilla port.

@anthonydillon

**Comment by anthonydillon** [comment]
@stgraber would you like the step-by-step instructions to collapse when you click the "Step by step instructions" title of the panel?

**Comment by stgraber** [comment]
Yes and same for the "Feedback" panel.
