### ISSUE TITLE
Switch Try it to xterm.js

### ISSUE THREAD

**Issue by techtonik** [lxc/linuxcontainers.org#291]
Try it demo would be more useful it it allowed copy/paste - https://github.com/lxc/lxd-demo-server/issues/5

https://github.com/xtermjs/xterm.js might be a drop-in replacement for current `term.js`, however it requires `npm` to start, so it is not entirely clear how to move it into our static website.

**Comment by stgraber** [comment]
It's not a drop-in replacement, I tried it a while back and after 2 hours of work on it still couldn't get it to work.

**Comment by techtonik** [comment]
Too bad it is still 2 hours of work to pick up from the point you've left it.

**Comment by techtonik** [comment]
The "Try it" web page is gone. The code is still there https://github.com/canonical/lxd-demo-server/
