### ISSUE TITLE
[info] is there some reference how the Simplestreams images.json is generated

### ISSUE THREAD

**Issue by erickeller** [lxc/linuxcontainers.org#303]
I am wondering if you could point out to the source code who generates the following file 
https://images.linuxcontainers.org/streams/v1/images.json

looking for simplestreams in the code only gives a list of yaml file

do you use `juju metadata generate-image` or similar approach?
any signed sjson available?

Kind regards

**Comment by stgraber** [comment]
Unfortunately no, the code that generates this particular json file is a horrible mess and includes a bunch of secret keys and other internal details... The code generating just the json isn't particularly difficult though, it's just a big python dict that we fill with all the right fields and then dump to a .json on disk.

I hope that in time we can maybe add the index generation into our new `distrobuilder` tool, which would then let us deprecate that horrible script and have something that everyone else can use to build and publish custom images.

As for sjson, we do not publish nor consume those, we rely on https for validation of the index files and then use the sha256 hashes to validate the actual image. The images can alternatively be validated using gpg though as those are indeed signed.

Generating and publish sjson shouldn't be particularly hard for us though, so we may just do that, even if we don't consume them ourselves.

**Comment by stgraber** [comment]
We now have:
 - https://images.linuxcontainers.org/streams/v1/index.json.gpg
 - https://images.linuxcontainers.org/streams/v1/images.json.gpg
 - https://images.linuxcontainers.org/streams/v1/index.sjson
 - https://images.linuxcontainers.org/streams/v1/images.sjson

**Comment by stgraber** [comment]
signed with the same key we use for all the other files on that server
