### ISSUE TITLE
"Try it online" page is erroring

### ISSUE THREAD

**Issue by caldav** [lxc/linuxcontainers.org#315]
The [/lxd/try-it page](https://linuxcontainers.org/lxd/try-it/) is showing an error message instead of the demo.

![](https://user-images.githubusercontent.com/36884067/42222252-842f332a-7ecc-11e8-9e09-9bd9e9df08c6.png)

**Comment by stgraber** [comment]
Fixed, some issue with Ubuntu Core was preventing the backend servers from booting up properly, now reverted to an older build.
