### ISSUE TITLE
[Request] Move or link docs here

### ISSUE THREAD

**Issue by toby63** [lxc/linuxcontainers.org#410]
I noticed that the [documentation](https://linuxcontainers.org/lxd/docs/master/) is saved within the repos of [lxd](https://github.com/lxc/lxd/tree/master/doc) etc.

While I understand that it is this way, because developers maybe favor it to be near the code, I still wanted to suggest to move, or at least link it here.
There already seems to be a place for this:
https://github.com/lxc/linuxcontainers.org/tree/master/content/lxd/docs

Reasons/Advantages:
* the documentation is also a part of the website
* issues regarding the docs could be placed here
* docs could be downloaded with the website (?: I don't know if git can follow links, i never tested that)

**Comment by stgraber** [comment]
The doc is built from the main git repo and published at https://linuxcontainers.org/lxd/docs/master/

We will not be moving it away from the code as having things separate makes tracking per-release documentation near impossible.

The directory in the repo exists as a placeholder so the script that syncs it from the code has somewhere to write it to :)
