### ISSUE TITLE
[Feature Request] Search machine

### ISSUE THREAD

**Issue by toby63** [lxc/linuxcontainers.org#416]
It would be good to implement a way to search the website.

I remember reading about it (found it here: https://discuss.linuxcontainers.org/t/new-self-hosted-documentation-site/5540/4).
@stgraber suggested implementing a google search.
For privacy reasons I would advocate for [DuckDuckgo](https://duckduckgo.com/about) or similar instead.

Regarding the difficulty implementing it, could you maybe implement a search box, like
https://duckduckgo.com/search_box ?
It works with iframe.

Update:
Example for implementation:
<code>
<iframe src="https://duckduckgo.com/search.html?width=220&site=https://linuxcontainers.org&prefill=Search with DuckDuckGo&bgcolor=ffffff" style="overflow:hidden;margin:0;padding:0;width:278px;height:40px;" frameborder="0"></iframe>
</code>

**Comment by stgraber** [comment]
Yeah, we may be able to put something like that in the footer or something.
As the vast majority of visitors are already coming in from search engines, there's not much benefit from making it super visible at the top.

**Comment by toby63** [comment]
One idea I had:
What about adding a search symbole to the top?
This way it is smaller, but still visible.

I don't know though if we can easily add an iframe inside a drop-down menu :thinking:, this would be the nicest solution imo.
But as an alternative we might jump to the search bar instead.

**Comment by toby63** [comment]
I have also found this in the Vanilla Framework:
https://vanillaframework.io/docs/patterns/search-box

:thinking: But I don't know enough about the Framework to know how it works behind the scenes.
Like is further work necessary or does it simply work out the box.

**Comment by stgraber** [comment]
That's likely just a widget that you can use with some kind of search engine on your site.
We don't have any such engine so we either need to go to Google or similar, or we need to find something else we could use for that.

Ideally, we'd have some kind of tool we can run against `content/` which produces a static search index file of some sort which can then be accessed from Javascript, letting us get a decent search without needing to do anything server-side or relying on 3rd party services. I don't know what solutions already exist for this though.
