### ISSUE TITLE
[Discussion] remote servers section in documentation

### ISSUE THREAD

**Issue by toby63** [lxc/linuxcontainers.org#431]
While I was editing getting-started-cli I noticed that the different types of remote servers are not clearly seperated.

I suggest seperating them with different commands, for example:
* `lxc imageserver` - for imageservers 
(The list could include LXD-Servers as well, but on a seperate list below the regular imageservers)
* `lxc remote` - only for LXD servers

Advantages:
* This way we can explain the difference better to new users
* A clear seperation avoids confusion
* People who use many LXD-Servers or imageservers have a clear overview as well

**Comment by stgraber** [comment]
Moving this discussion over to linuxcontainers.org repo.

**Comment by toby63** [comment]
> Dealing with remotes in general can probably be kept for the advanced section.

Ok, will do.

> The getting started guide probably ought to cover things like virtual machines though.

You mean, how to implement already existing images (for example from other vm-software like qemu, kvm etc.)?

**Comment by stgraber** [comment]
No, I mean showing examples of starting VMs with LXD instead of just containers.

The --vm stuff added in 3.19 or so.

**Comment by toby63** [comment]
> No, I mean showing examples of starting VMs with LXD instead of just containers.

That is already included in the todo list for #412 .

**Comment by toby63** [comment]
I close this as it is decided to put the topics about remote servers and more image options into the advanced guide.

**Comment by toby63** [comment]
@stgraber 
Reopening this,
because some questions came across my way while reading on this topic for the advanced guide.
Regarding the methods you mentioned (https://github.com/lxc/linuxcontainers.org/issues/431#issuecomment-643373091):

* `public`: How can one setup a LXD-Server to be only available for image publishing?
* `unix`: I assume this is the local method? So not intended for network
* `tls`: I assume this is the standard method with:
    ```
    lxc config set core.https_address "[::]"
    lxc config set core.trust_password some-password
    ```
    Am I correct?
* `candid`: I found [this tutorial](https://ubuntu.com/tutorials/candid-authentication-lxd#1-overview): 
    1. Is it still up to date?
    2. Can I link to that in the Advanced Guide? Or would you prefer a seperate howto of that? (I wouldn't write that by the way, because I don't know enough about that).
* `candid+rbac`: Sounds very useful, but I read that it is only supported with Canonical’s RBAC, is that correct?
  I also could not find much information about it, only this: https://ubuntu.com/blog/multi-tenancy-in-maas , so I assume it is used in combination with maas?
* `simplestreams`: You said: `Only implements images and has no authentication support at this time.` yet I see in `lxc remote add` : 
   ```
   Basic authentication can be used when combined with the "simplestreams" protocol:
    lxc remote add some-name https://LOGIN:PASSWORD@example.com/some/path --protocol=simplestreams
  ```
  Can you explain what you meant?

- Can you also explain whether the simplestreams protocol can used for an LXD-Server as well or is it just for seperate "only-image"-servers, mainly [this one](https://github.com/Avature/lxd-image-server)?

**Comment by stgraber** [comment]
1) Public image server used only for images. That's a normal LXD but without any storage pools or networks.
2) `unix` is indeed what's used for local connection
3) `tls` yep
4) Yeah, tutorial still looks correct. Pointing to the tutorial is fine. If it gets outdated we'll want it updated anyway.
5) It indeed only works with Canonical RBAC. You don't need MAAS for it but you do need access to the RBAC product which only comes with paid Ubuntu Advantage subscription at this time (I wish we had a proper page for it and that like all our other paid products we'd have a free version for < 5 systems but that's not the case yet...)
6) Ah yeah, basic http authentication does work, though LXD is completely unaware of it and your login/password will be passed directly to any LXD server you use the remote with, the LXD server is similarly unaware of it being credentials so will happily log them and potentially put them in user visible location. Proper auth support would be either certificate based or supporting some kind of token which does not get logged all over the place :)
7) LXD itself doesn't offer images over the simplestreams protocol, it only knows how to consume images available from them. There are a number of implementation of servers, ranging from just some static JSON files (like cloud-images.ubuntu.com and images.linuxcontainers.org) to more complex servers that generate the files on demand.

**Comment by toby63** [comment]
Thank you for the information.

> 1. Public image server used only for images. That's a normal LXD but without any storage pools or networks.

Sry for asking but where are the images stored without storage pools and how does the connection work without networks?
The point is, maybe the guide should describe how to set up such a public-server.

> 5. [...] the RBAC product which only comes with paid Ubuntu Advantage subscription at this time (I wish we had a proper page for it and that like all our other paid products we'd have a free version for < 5 systems but that's not the case yet...)

:thinking: Ok, unfortunate indeed, but would you like this method to be mentioned in the advanced guide? 
Still I would like to have some websites I can link to.
Maybe we wait until your ubuntu colleagues have set something up (if that is even planned?)?

**Comment by stgraber** [comment]
`snap install lxd && lxc config set core.https_address :8443` is all it takes for a LXD instance to be functional as an image server.
Images are always stored outside of storage pools and networks are only used to attach instances.

For RBAC, maybe just link to https://linuxcontainers.org/lxd/docs/master/security#role-based-access-control-rbac for now
