### ISSUE TITLE
The site uses an old version of the Vanilla Framework

### ISSUE THREAD

**Issue by fitojb** [lxc/linuxcontainers.org#444]
Notably, the Vanilla Framework has, for a few releases now, natively supported dropdown navigation items in its header bar, so the custom solution used here can be dropped.

**Comment by stgraber** [comment]
We've usually been letting the vanilla team deal with such updates themselves. So hopefully someone will do it at some point soon.

**Comment by fitojb** [comment]
cc @canonical-web-and-design

**Comment by toby63** [comment]
Any update on this?

Or am I missunderstanding something?

I still see:

```
<link rel="stylesheet" href="https://assets.ubuntu.com/v1/vanilla-framework-version-1.8.0.min.css" />
```

in https://github.com/lxc/linuxcontainers.org/blob/master/templates/common/base.tpl.html

**Comment by stgraber** [comment]
Usually we would have someone from @canonical-web-and-design handle the transition as they have in the past.

**Comment by edlerd** [comment]
I'll pick this one.

**Comment by fitojb** [comment]
Thanks @edlerd!
