### ISSUE TITLE
Some Documentation section navigation anchor links are non-functional (special character problems?).

### ISSUE THREAD

**Issue by tim-seoss** [lxc/linuxcontainers.org#446]
When navigating the master docs at:

https://linuxcontainers.org/lxd/docs/master/instances#hugepage-limits-via-limitshugepagessize

... some of the quick navigation (anchor) links displayed in the right-hand column don't function (such as the one which produced the link included above) - apparently due to the use of characters such as `/` and `[` in the section names.

**Comment by stgraber** [comment]
Moved over to the website.

I did notice this in the past and it's a bit unclear where we need to fix this.
If we change the links in markdown, we'll break the rendering on Github which feels wrong, so it's most likely something to try and work out in markdown to html generator on the website.
