### ISSUE TITLE
[Request] Changes to the Readme.md

### ISSUE THREAD

**Issue by toby63** [lxc/linuxcontainers.org#461]
**Additions:**
- mention that we would like to see translations (right now this is not mentioned)
   - and maybe a status of translations and participants (if possible)
- Writing Guidelines:
   - mostly Markdown with a bit of html
   - I could add some specifics I included, such as special css-classes for notes etc.
   - different "styles" for website versus documentation
- link directly to open issues, for example: Issue about the Advanced Guide
- mention Ideas and Feature Requests (and not just  "Bug Reports")

**Corrections:**
- `python3-markdown (<3.0.0)`, is not `<3.0.0` anymore

**Comment:**
I can work on Pull requests for most of this, but I wanted to hear oppinions first :smile:.

**Comment by toby63** [comment]
@stgraber What is your oppinion on [sparse-checkouts](https://www.git-scm.com/docs/git-sparse-checkout)?

I am thinking about adding it to the git clone instructions in README.md, because the `Downloads`-folder is quite big and unnecessary for people who want to edit the website.

**Comment by stgraber** [comment]
Yeah, that should be fine. Unless they're working on the rendering of the download pages that is.

**Comment by toby63** [comment]
Added with #463 and #464.
