### ISSUE TITLE
[Feature Request] Add manpages for LXD

### ISSUE THREAD

**Issue by toby63** [lxc/linuxcontainers.org#471]
In recent time we had some discussions in the forums, where users would like to have more information regarding the available commands and details on them (flags etc.).

I think it would be useful to add manpages to the website for a better workflow while reading the **Advanced Guide** for example.
We could link to the manpages to give users more information on available flags and options for commands.
This way we don't have to include all options in the Guides themselves, because:
1. The flags etc. might change in the future.
2. We could keep the guides short.

**Comment by stgraber** [comment]
We have automated scripts that handle that for LXC, the rendering on the website isn't the prettiest (man2html isn't all that great) but it's good enough.

For LXD, I just pushed https://github.com/lxc/lxd/pull/8397 which then lets you do `lxc manpage --format=md /tmp/some-dir`

**Comment by toby63** [comment]
For clarification:
Do you plan to implement automated scripts for LXD too?
Or should I ran and add the manpages manually?
Or was this just intended for personal use?

**Comment by stgraber** [comment]
I'll have this command run automatically on the server at some point, then we can add it to the website.

**Comment by toby63** [comment]
Ok, I will probably add links to the existing pages (Advanced Guide etc.), once it's ready.

> the rendering on the website isn't the prettiest (man2html isn't all that great) but it's good enough.

I think it looks quite good.
