### ISSUE TITLE
nova-lxd charm has been deprecated

### ISSUE THREAD

**Issue by szeestraten** [lxc/linuxcontainers.org#477]
Hi, usage of nova-lxd charm in the OpenStack charms project has been deprecated for a while: https://docs.openstack.org/charm-guide/latest/1907.html#nova-lxd-charm

It should probably be removed from the website.

**Comment by toby63** [comment]
@stgraber I think that seems to be correct: https://opendev.org/x/nova-lxd/

**Comment by stgraber** [comment]
Yeah, we can drop the openstack bits. If we want to list external LXD integrations, it'd probably make sense to have a package which lists:
 - Ansible
 - Terraform
 - Puppet
 - Juju
 - OpenNebula

For the major ones I can think of.

**Comment by toby63** [comment]
So a single page that lists the integrations?
And then we link to external docs like: https://juju.is/docs/olm/lxd ?
(If something is available.)

**Comment by stgraber** [comment]
Yep, something like that would be great!

**Comment by toby63** [comment]
@stgraber Can be closed.
