### ISSUE TITLE
All links in sidebar at https://linuxcontainers.org/lxd/docs/master/ are broken

### ISSUE THREAD

**Issue by pajot** [lxc/linuxcontainers.org#480]
All the links from the sidebar menu at [https://linuxcontainers.org/lxd/docs/master/](https://linuxcontainers.org/lxd/docs/master/) that I have tested result in 404 errors.

Example:
[https://linuxcontainers.org/lxd/docs/master/faq](https://linuxcontainers.org/lxd/docs/master/faq)

**Comment by stgraber** [comment]
Thanks for reporting this. We moved the website to new servers yesterday, looks like we have some rewrite rules missing...

**Comment by stgraber** [comment]
Fixed now.
