### ISSUE TITLE
LXD Contribute page links to wrong URL

### ISSUE THREAD

**Issue by ru-fu** [lxc/linuxcontainers.org#492]
https://linuxcontainers.org/lxd/contribute/ links to https://github.com/lxc/lxd/blob/master/contributing.md, which is a symbolic link, so the content is not displayed. 
The Contribute page should link directly to https://github.com/lxc/lxd/blob/master/doc/contributing.md.

**Comment by stgraber** [comment]
Good catch, fixed!
