### ISSUE TITLE
[Todo] getting-started-cli.md: Exchange lxd init --auto for newer versions

### ISSUE THREAD

**Issue by toby63** [lxc/linuxcontainers.org#499]
Related to https://github.com/lxc/lxd/issues/9109

With LXD 4.18 the `lxd init --auto` flag will change to `lxd init --minimal`.

**Comment by stgraber** [comment]
probably will want to wait for 4.0.8 to be out too so we have the new flag in both latest and 4.0

**Comment by toby63** [comment]
Ok, I guess I will do it in two steps:

1. When 4.18 is released, I will add a note that in version 4.18 and newer the new command is used, while for older versions the old command should be used.
2. When 4.0.8. is released, we can probably change it to the new command entirely.

**Comment by toby63** [comment]
I created PR #515 for intermediate step 1.

Step 2 will follow once 4.0.8 is released.
