### ISSUE TITLE
SSL cert for images.linuxcontainer.org is expired

### ISSUE THREAD

**Issue by grzegorznowak** [lxc/linuxcontainers.org#512]
hey sorry guys wasn't sure whom to post this, so doing it here. 
Basically as title says. It's been down for 4 hours now as of the time of writing this, preventing downloads of lxd images.

**Comment by tomponline** [comment]
Duplicate of https://github.com/lxc/lxd/issues/9175

**Comment by grzegorznowak** [comment]
I can confirm it's working now, so closing.
