### ISSUE TITLE
Link to Jobs section on forum

### ISSUE THREAD

**Issue by toby63** [lxc/linuxcontainers.org#523]
We could add a page under: https://linuxcontainers.org/jobs for example.

And we could link to the forum section: https://discuss.linuxcontainers.org/c/jobs/17

**Comment by stgraber** [comment]
Yeah, we don't want to duplicate the information but having it link to the forum would be fine.

**Comment by toby63** [comment]
Should it be added to the footer?
Or should it be added to: #438 ?
Or something else?

**Comment by stgraber** [comment]
We could probably turn `Home` into a menu and have that then contain `Home page`, `About us` and `Jobs` or something along those lines.
