### ISSUE TITLE
lxd/try-it page not loading - CORS header ‘Access-Control-Allow-Origin’ missing

### ISSUE THREAD

**Issue by kimfaint** [lxc/linuxcontainers.org#549]
I noticed the lxd/try-it page is not loading today.
![tryit_cors_timeout](https://user-images.githubusercontent.com/1551809/136156977-948f9458-3526-476b-9436-0822c1ea3634.png)
![tryit_cors_network](https://user-images.githubusercontent.com/1551809/136156993-855af8e8-f2c1-43ec-810e-f0a3d91ecba7.png)
```Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://lxd-demo.linuxcontainers.org/1.0/start?terms=1918e95a87fba7ca6a8860e2c6fe0fd47c259da8de750cac2c0eb905ebed0689. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).```

**Comment by stgraber** [comment]
Is it still not loading?

**Comment by kimfaint** [comment]
It's loading now. :+1:
