### ISSUE TITLE
Please remove Avature's lxd-image-server from documentation

### ISSUE THREAD

**Issue by antifob** [lxc/linuxcontainers.org#592]
Hi,

I've been looking at Avature's lxd-image-server (referenced in the Advanced Guide section) for the past hour only to find out that it's broken. It is, sadly, badly designed, written, documented, released and maintained. That project's first issue was quite indicative: https://github.com/Avature/lxd-image-server/issues/1 (see the first and last 3 comments). I believe a complete rewrite would less of a waste of time, but...

Where is Simplestreams specified? Are there any simple and sane implementations around? I keep seeing it used at Canonical and apparently being "widely" used, and maybe it's just me, but it seems to be a mostly internal/private technology.

In the mean time, please consider removing that project from the documentation. It's been broken for around 3 years now.

Thanks :)

Note that I considered a PR, but I don't have knowledge of any alternative, and that would remove an important chunk of the docs.

**Comment by stgraber** [comment]
@ru-fu

**Comment by stgraber** [comment]
I believe https://git.launchpad.net/simplestreams/tree/ is the main repository for simplestreams and has some details in doc/ and examples/ but it's pretty far from a clear documentation.

**Comment by antifob** [comment]
#593 Does it for me. Thanks. :)

Small question. I was just looking at `images.json` served from `images:`. It should be pretty easy to write a generator, but noticed the `lxd_requirements` dictionary which, for some VMs, contain `secure_boot: false`. I couldn't find how this field is populated. Are the `config` parameters that are automatically added to instances and figured out through testing on lxd's part?

My primary concern about writing a generator is that it's heavily dependent on what lxd expects. For example, if a field is added, removed, re-interpreted, etc. there's a potentially breaking issue. Is there a spec/schema definition somewhere that I could use.

**Comment by stgraber** [comment]
Sadly not really. The simplestreams repo is as close to a spec as it gets. For specific vendor extensions like the requirements key, it's usually documented in vendor docs.

In this case, lxd_requirements gets translated to requirements.XYZ keys with the valid keys and values listed at https://linuxcontainers.org/lxd/docs/latest/image-handling/#special-image-properties
