### ISSUE TITLE
https://linuxcontainers.org/lxd/docs/master/ throwing 403 Forbidden error message

### ISSUE THREAD

**Issue by jnewman-altair** [lxc/linuxcontainers.org#600]
At some point over the weekend, the documentation for LXD has become inaccessible. 
https://linuxcontainers.org/lxd/docs/master/ - [403 Forbidden]
![image](https://user-images.githubusercontent.com/2013876/179556461-a75adb81-3a35-44a0-9296-5f3f27208fe6.png)

**Comment by tomponline** [comment]
Thanks for letting us know, we are aware and investigating.

**Comment by stgraber** [comment]
Fixed!
