### ISSUE TITLE
Broken links in setup options

### ISSUE THREAD

**Issue by waveform80** [lxc/linuxcontainers.org#609]
Under [Interactive setup options](https://linuxcontainers.org/lxd/getting-started-cli/#interactive-setup-options) there is a table. Two of the links in the "Storage pools" row appear to be broken (or don't go where they're meant to), specifically:

* "Comparison of methods" and
* "Backend comparison chart"

I *suspect* these are meant to point to https://linuxcontainers.org/lxd/docs/master/explanation/storage/#data-storage-location and https://linuxcontainers.org/lxd/docs/master/reference/storage_drivers/#feature-comparison but which goes to which I'm unsure (as the headings have evidently changed), and I couldn't (quickly) figure out how to reference those locations correctly in the source.

**Comment by tomponline** [comment]
@ru-fu

**Comment by ru-fu** [comment]
Thanks, good catch!
