### ISSUE TITLE
information about current lxc?

### ISSUE THREAD

**Issue by frevi** [lxc/linuxcontainers.org#611]
I'm on Ubuntu 22.04 all up to date; lxd 5.5. Trying to create a (win10) vm. I'm guessing that the lxc pages on this site are pretty out of date because the lxc commands as posted usually don't work, and trying to deduce syntax that doesn't throw errors, much less accomplishes simple tasks (with my limited linux experience) takes a really long time, almost as long as getting useful help from posting to forums. I keep seeing references to linux 18.04 as if that's the new release you need for it. I have things I actually need to do with the vm (with deadlines even,), though of course I'd love to spend hours and weeks and months learning the ropes. "Still trying to get a vm running" is wearing pretty thin with the higher-ups after only a month. I know, everyone should just chill.

Does anyone know a way for someone like me who hasn't been following the lxc code evolution in detail for years to find out the currently supported complete set of commands, what they do, flags, options, or god forbid documentation about how to actually use it for real, in the wild, to accomplish something useful?

**Comment by stgraber** [comment]
You're confusing LXC (commands are `lxc-*`) and LXD (command is `lxc`).

Which is indeed rather confusing but not something we can do much about :(

https://discuss.linuxcontainers.org/t/comparing-lxd-vs-lxc/24 has a bit more of an explanation.
The LXD documentation is at https://linuxcontainers.org/lxd/docs/latest/
