### ISSUE TITLE
Navigation menu not functioning as expected

### ISSUE THREAD

**Issue by VergilYotov** [lxc/linuxcontainers.org#617]
The navigation menu does not unfold and clicking the items does nothing.

![Screenshot from 2022-10-01 08-43-53](https://user-images.githubusercontent.com/1883710/193398883-1b1e329e-1883-4b65-b8eb-0c7dc4d87258.png)

I am using the Firefox 105 deb on Ubuntu 20.04.05

Package: firefox
Version: 105.0+build2-0ubuntu0.20.04.1

Expected behaviour:
![Screenshot from 2022-10-01 08-48-55](https://user-images.githubusercontent.com/1883710/193399102-5de60071-3f2b-461f-bd65-05967275b26b.png)

**Comment by toby63** [comment]
I am on Manjaro Linux with Firefox 105.0.1 and everything seems to work fine.

**Comment by stgraber** [comment]
@VergilYotov can you try a force refresh of the page (ctrl+shift+r)?
It may be that your browser has a cached version of the old CSS or JS code.

**Comment by VergilYotov** [comment]
@stgraber Thanks that fixed it! It was a stuck Firefox update. Restarted the browser and refreshed the cache. It works as expected now.
