### ISSUE TITLE
Reduce learner confusion by renaming the lxc tool to something else, e.g., lxdclient

### ISSUE THREAD

**Issue by hgolden** [lxc/linuxcontainers.org#619]
Naming the lxd client 'lxc' is a source of confusion to anyone trying to understand Linux containers. I suggest you change the name to something that doesn't include 'lxc'. How about 'lxcclient' or 'lxd-client'?

**Comment by stgraber** [comment]
Yeah, no, that's not going to happen :)

We definitely agree on the confusion but the decision was made pretty far up and isn't something we're going to be changing 8 years into a project.
