### ISSUE TITLE
Add German translation to website

### ISSUE THREAD

**Issue by WebSnke** [lxc/linuxcontainers.org#664]
Hi, I would love to translate this website to German.
How would I do that?

I think it would also be a good idea to automatically redirect the user to the respective translated page.

**Comment by stgraber** [comment]
You should make a fork of the repository, make sure that you can build the website and run it locally, then to add a translation, your best bet is to look at the Japanese (`.ja`) files inside the content/ folder to get an idea of how to handle translating the website.
