### ISSUE TITLE
Add Fanctl?

### ISSUE THREAD

**Issue by emilebosch** [lxc/linuxcontainers.org#72]
Hi guys, im pretty impressed with all the work you've done so far on LXC, LXD and now FANCTL. Shall we add them to linuxcontainers org?

**Comment by techtonik** [comment]
FANCTL? Can you give a link, please?

**Comment by ingobaab** [comment]
Mark Shuttleworth (designed and) wrote about it:
http://www.markshuttleworth.com/archives/1471

**Comment by techtonik** [comment]
Read it. I don't how is solves the problem of depleting IPv4 addresses - it still needs to allocate them all. Is it just a two-way NAT?
