### ISSUE TITLE
TOC wrongly flattened

### ISSUE THREAD

**Issue by bensmrs** [lxc/linuxcontainers.org#726]
The TOC in https://linuxcontainers.org/incus/news/ is flattened, making it very hard to differentiate between titles and sub-titles. I think we should use nested lists for the TOC.

**Comment by stgraber** [comment]
Ah yeah, that's not very useful...

I don't know about having it support proper nesting, but it certainly should be made to only pick up the news entry titles and not anything inside of the news entries.

**Comment by bensmrs** [comment]
If #728 looks good to you, I’ll modify the other locales

**Comment by stgraber** [comment]
Closing as this has been resolved by #728
