### ISSUE TITLE
lxd already on Gentoo

### ISSUE THREAD

**Issue by benaryorg** [lxc/linuxcontainers.org#77]
I don't know if there are already more distributions but lxd is already available among Gentoos main packages as opposed to ["only Ubuntu"](https://github.com/lxc/linuxcontainers.org/blob/master/content/lxd/getting-started-cli.md#other-distributions).

**Comment by stgraber** [comment]
ah, cool, feel free to send a patch.

**Comment by benaryorg** [comment]
Here you are.

Feel free to edit it any time.
